In [15]:
import sys
from pyprojroot import here
sys.path.insert(0, str(here()))

In [16]:
import copy
import optuna
import numpy as np
from transformers import AutoTokenizer
import time

from src.train import train_single_fold, tokenize_df
from src.config import load_config
from src.data_holdout import get_pooled_df, get_fold_from_disk

import yaml
import torch
from datasets import Dataset
from pyprojroot import here
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
)

from sklearn.metrics import f1_score
from peft import LoraConfig, get_peft_model, TaskType

In [17]:
MODEL_NAME = "roberta-base"

In [12]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=3)
for name, module in model.named_modules():
    if "query" in name or "value" in name:
        print(name)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1864.40it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

roberta.encoder.layer.0.attention.self.query
roberta.encoder.layer.0.attention.self.value
roberta.encoder.layer.1.attention.self.query
roberta.encoder.layer.1.attention.self.value
roberta.encoder.layer.2.attention.self.query
roberta.encoder.layer.2.attention.self.value
roberta.encoder.layer.3.attention.self.query
roberta.encoder.layer.3.attention.self.value
roberta.encoder.layer.4.attention.self.query
roberta.encoder.layer.4.attention.self.value
roberta.encoder.layer.5.attention.self.query
roberta.encoder.layer.5.attention.self.value
roberta.encoder.layer.6.attention.self.query
roberta.encoder.layer.6.attention.self.value
roberta.encoder.layer.7.attention.self.query
roberta.encoder.layer.7.attention.self.value
roberta.encoder.layer.8.attention.self.query
roberta.encoder.layer.8.attention.self.value
roberta.encoder.layer.9.attention.self.query
roberta.encoder.layer.9.attention.self.value
roberta.encoder.layer.10.attention.self.query
roberta.encoder.layer.10.attention.self.value
roberta.encoder.layer.11.attention.self.query
roberta.encoder.layer.11.attention.self.value

## Test query, value vector only vs all linear layers

### Checked to make sure had correct names for query/vector

In [13]:
# open shared settings
with open(here("configs/base.yaml"), "r") as f:
    base_data = yaml.full_load(f)

# get df
full_df = get_pooled_df()

# same pattern as collaborator: all folds
train_folds, val_folds = get_fold_from_disk(full_df)

# load tokenizer and write tokenize function
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_fold(df):
    ds = Dataset.from_pandas(df, preserve_index=False)

    def _tokenize(examples):
        return tokenizer(
            examples["abstract_conclusion"],
            examples["press_release_conclusion"],
            truncation=True,
            padding="max_length",
            max_length=base_data["max_length"],
        )

    cols_to_remove = [c for c in ds.column_names if c != "exaggeration_label"]
    ds = ds.map(_tokenize, batched=True, remove_columns=cols_to_remove)
    ds = ds.rename_column("exaggeration_label", "labels")
    ds.set_format("torch")
    return ds

# tokenize all folds
train_ds = [tokenize_fold(df) for df in train_folds]
val_ds = [tokenize_fold(df) for df in val_folds]

for i in range(len(train_ds)):
    print(f"Fold {i}: train={len(train_ds[i])} val={len(val_ds[i])}")

# define metrics function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {"macro_f1": f1_score(labels, preds, average="macro")}

/workspace/exaggeration-detection/src/data_holdout.py:65: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(ENCODED_LABELS)
Map: 100%|██████████| 424/424 [00:00<00:00, 12176.80 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 11857.01 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 11179.89 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 10279.44 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 10792.87 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 7824.37 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 7689.32 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 8035.07 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 8523.70 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 8547.30 examples/s]

Fold 0: train=424 val=106
Fold 1: train=424 val=106
Fold 2: train=424 val=106
Fold 3: train=424 val=106
Fold 4: train=424 val=106

In [21]:


def run_quick_lora_test(target_modules, fold=0):
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=3
    )

    peft_config = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        target_modules=target_modules,
        r=8,
        lora_alpha=16,
        lora_dropout=0.05,
        bias="none",
    )

    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()

    training_args = TrainingArguments(
        output_dir=str(here("results/tmp_lora_test_roberta")),
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=2e-4,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        weight_decay=0.01,
        warmup_ratio=0.1,
        num_train_epochs=5,
        metric_for_best_model="macro_f1",
        fp16=True,
        seed=42,
        logging_steps=10,
        report_to="none",
        skip_memory_metrics=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds[fold],
        eval_dataset=val_ds[fold],
        compute_metrics=compute_metrics,
    )

    start = time.time()
    trainer.train()
    metrics = trainer.evaluate()
    elapsed = time.time() - start

    del trainer, model
    torch.cuda.empty_cache()

    return {
        "target_modules": target_modules,
        "runtime_min": elapsed / 60,
        "macro_f1": metrics["eval_macro_f1"],
    }

results_qv = run_quick_lora_test(["query","value"])
results_all = run_quick_lora_test(["query", "key", "value", "dense", "out_proj"])

print(results_qv)
print(results_all)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1598.77it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 887,811 || all params: 125,535,750 || trainable%: 0.7072

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2881.08it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,920,003 || all params: 126,567,942 || trainable%: 1.5170

{'target_modules': ['query', 'value'], 'runtime_min': 0.4382455150286357, 'macro_f1': 0.253411306042885}
{'target_modules': ['query', 'key', 'value', 'dense', 'out_proj'], 'runtime_min': 0.6489670475323995, 'macro_f1': 0.3186991869918699}

### Ran a small test first

In [6]:
def run_quick_lora_test(target_modules, fold=0):
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=3
    )

    peft_config = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        target_modules=target_modules,
        r=8,
        lora_alpha=16,
        lora_dropout=0.05,
        bias="none",
    )

    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()

    training_args = TrainingArguments(
        output_dir=str(here("results/tmp_lora_test_roberta")),
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=2e-4,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        weight_decay=0.01,
        warmup_ratio=0.1,
        num_train_epochs=5,
        metric_for_best_model="macro_f1",
        fp16=True,
        seed=42,
        logging_steps=10,
        report_to="none",
        skip_memory_metrics=True,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds[fold],
        eval_dataset=val_ds[fold],
        compute_metrics=compute_metrics,
    )

    start = time.time()
    trainer.train()
    metrics = trainer.evaluate()
    elapsed = time.time() - start

    del trainer, model
    torch.cuda.empty_cache()

    return {
        "target_modules": target_modules,
        "runtime_min": elapsed / 60,
        "macro_f1": metrics["eval_macro_f1"],
    }

results_qv = run_quick_lora_test(["query","value"])
results_all = run_quick_lora_test("all-linear")

print(results_qv)
print(results_all)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1428.80it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 887,811 || all params: 125,535,750 || trainable%: 0.7072

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1574.35it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,920,003 || all params: 126,567,942 || trainable%: 1.5170

{'target_modules': ['query', 'value'], 'runtime_min': 0.6380618373552959, 'macro_f1': 0.253411306042885}
{'target_modules': 'all-linear', 'runtime_min': 1.073991020520528, 'macro_f1': 0.3284566838783706}

### Then ran a bigger test on all 5 folds

In [14]:
def run_lora_5fold_test(target_modules, label):
    fold_scores = []
    fold_times = []

    for fold in range(5):
        model = AutoModelForSequenceClassification.from_pretrained(
            MODEL_NAME,
            num_labels=3
        )

        peft_config = LoraConfig(
            task_type=TaskType.SEQ_CLS,
            target_modules=target_modules,
            r=8,
            lora_alpha=16,
            lora_dropout=0.05,
            bias="none",
        )

        model = get_peft_model(model, peft_config)

        if fold == 0:
            print(f"\n=== {label} ===")
            model.print_trainable_parameters()

        training_args = TrainingArguments(
            output_dir=str(here(f"results/tmp_lora_compare_{label}/fold-{fold}")),
            eval_strategy="epoch",
            save_strategy="no",
            learning_rate=2e-4,
            per_device_train_batch_size=8,
            per_device_eval_batch_size=8,
            weight_decay=0.01,
            warmup_ratio=0.1,
            num_train_epochs=5, 
            fp16=True,
            seed=42,
            logging_steps=10,
            report_to="none",
            skip_memory_metrics=True,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_ds[fold],
            eval_dataset=val_ds[fold],
            compute_metrics=compute_metrics,
        )

        start = time.time()
        trainer.train()
        metrics = trainer.evaluate()
        elapsed = time.time() - start

        fold_scores.append(metrics["eval_macro_f1"])
        fold_times.append(elapsed / 60)

        print(
            f"{label} | fold {fold} | "
            f"macro_f1={metrics['eval_macro_f1']:.4f} | "
            f"runtime_min={elapsed/60:.2f}"
        )

        del trainer, model
        torch.cuda.empty_cache()

    return {
        "label": label,
        "target_modules": target_modules,
        "fold_scores": fold_scores,
        "mean_macro_f1": float(np.mean(fold_scores)),
        "std_macro_f1": float(np.std(fold_scores)),
        "fold_times_min": fold_times,
        "mean_runtime_min": float(np.mean(fold_times)),
        "total_runtime_min": float(np.sum(fold_times)),
    }

results_qv = run_lora_5fold_test(["query", "value"], "qv")
results_all = run_lora_5fold_test("all-linear", "all_linear")

print("\nQ/V results:")
print(results_qv)

print("\nAll-linear results:")
print(results_all)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1319.95it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

=== qv ===
trainable params: 887,811 || all params: 125,535,750 || trainable%: 0.7072

qv | fold 0 | macro_f1=0.2534 | runtime_min=0.65

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1413.91it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

qv | fold 1 | macro_f1=0.2534 | runtime_min=0.67

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1258.50it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

qv | fold 2 | macro_f1=0.2534 | runtime_min=0.60

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1588.50it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

qv | fold 3 | macro_f1=0.2534 | runtime_min=0.61

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1167.74it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

qv | fold 4 | macro_f1=0.2534 | runtime_min=0.67

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1342.81it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

=== all_linear ===
trainable params: 1,920,003 || all params: 126,567,942 || trainable%: 1.5170

all_linear | fold 0 | macro_f1=0.3187 | runtime_min=1.08

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2095.62it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

all_linear | fold 1 | macro_f1=0.3049 | runtime_min=1.00

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2628.12it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

all_linear | fold 2 | macro_f1=0.3092 | runtime_min=1.11

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1611.58it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

all_linear | fold 3 | macro_f1=0.2534 | runtime_min=1.12

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1333.91it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

all_linear | fold 4 | macro_f1=0.2534 | runtime_min=1.01

Q/V results:
{'label': 'qv', 'target_modules': ['query', 'value'], 'fold_scores': [0.253411306042885, 0.253411306042885, 0.253411306042885, 0.253411306042885, 0.253411306042885], 'mean_macro_f1': 0.253411306042885, 'std_macro_f1': 0.0, 'fold_times_min': [0.6537256518999736, 0.6718911528587341, 0.5995204528172811, 0.6142852505048116, 0.668046506245931], 'mean_runtime_min': 0.6414938028653463, 'total_runtime_min': 3.2074690143267315}

All-linear results:
{'label': 'all_linear', 'target_modules': 'all-linear', 'fold_scores': [0.3186991869918699, 0.30487173800547057, 0.30921855921855923, 0.253411306042885, 0.253411306042885], 'mean_macro_f1': 0.2879224192603339, 'std_macro_f1': 0.02853085447742718, 'fold_times_min': [1.0799602468808491, 1.0006040970484416, 1.1068783442179362, 1.1215750654538472, 1.0120890974998473], 'mean_runtime_min': 1.0642213702201844, 'total_runtime_min': 5.321106851100922}

### With more training epochs, using all-linear was clear winner

## Full Optuna Experiment

In [26]:

# open shared settings
with open(here("configs/base.yaml"), "r") as f:
    base_data = yaml.full_load(f)

# get df
full_df = get_pooled_df()

# same pattern as collaborator: all folds
train_folds, val_folds = get_fold_from_disk(full_df)

# load tokenizer and write tokenize function
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize_fold(df):
    ds = Dataset.from_pandas(df, preserve_index=False)

    def _tokenize(examples):
        return tokenizer(
            examples["abstract_conclusion"],
            examples["press_release_conclusion"],
            truncation=True,
            padding="max_length",
            max_length=base_data["max_length"],
        )

    cols_to_remove = [c for c in ds.column_names if c != "exaggeration_label"]
    ds = ds.map(_tokenize, batched=True, remove_columns=cols_to_remove)
    ds = ds.rename_column("exaggeration_label", "labels")
    ds.set_format("torch")
    return ds

# tokenize all folds
train_ds = [tokenize_fold(df) for df in train_folds]
val_ds = [tokenize_fold(df) for df in val_folds]

for i in range(len(train_ds)):
    print(f"Fold {i}: train={len(train_ds[i])} val={len(val_ds[i])}")

# define metrics function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {"macro_f1": f1_score(labels, preds, average="macro")}

# def build_lora_model():
#     model = AutoModelForSequenceClassification.from_pretrained(
#         MODEL_NAME,
#         num_labels=3
#     )

#     # LoRA applied broadly to linear layers
#     peft_config = LoraConfig(
#         task_type=TaskType.SEQ_CLS,
#         target_modules="all-linear",
#         r=16,                # placeholder, overwritten per trial below
#         lora_alpha=32,       # placeholder, overwritten per trial below
#         lora_dropout=0.05,   # placeholder, overwritten per trial below
#         bias="none",
#     )

#     model = get_peft_model(model, peft_config)
#     return model

# set up Optuna objective
def objective(trial):
    folds_to_run = [0, 1, 3] # folds chosen based on previous experiments

    # LoRA-specific search space
    lr = trial.suggest_float("learning_rate", 1e-5, 5e-4, log=True)
    batch_size = trial.suggest_categorical("per_device_train_batch_size", [8])
    weight_decay = trial.suggest_float("weight_decay", 0.0, 0.1)
    warmup_ratio = trial.suggest_float("warmup_ratio", 0.05, 0.2)
    num_epochs = 8

    lora_r = trial.suggest_categorical("lora_r", [2, 4, 8, 16])
    lora_alpha = trial.suggest_categorical("lora_alpha", [4, 8, 16, 32])
    lora_dropout = trial.suggest_categorical("lora_dropout", [0.0, 0.05, 0.1])

    f1_scores = []
    fold_times_min = []

    for fold in folds_to_run:
        fold_start = time.time()
        model = AutoModelForSequenceClassification.from_pretrained(
            MODEL_NAME,
            num_labels=3
        )

        peft_config = LoraConfig(
            task_type=TaskType.SEQ_CLS,
            target_modules=["query", "key", "value", "dense", "out_proj"], #approximation of all linear, get same results  in testing
            r=lora_r,
            lora_alpha=lora_alpha,
            lora_dropout=lora_dropout,
            bias="none",
        )

        model = get_peft_model(model, peft_config)

        # confirm correct number of trainable parameters
        if fold == 0:
            model.print_trainable_parameters()

        training_args = TrainingArguments(
            output_dir=str(here(f"results/optuna/roberta_lora/trial-{trial.number}/fold-{fold}")),
            eval_strategy=base_data["eval_strategy"],
            save_strategy="no",              # no checkpoints this time
            learning_rate=lr,
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            weight_decay=weight_decay,
            warmup_ratio=warmup_ratio,
            num_train_epochs=num_epochs,
            metric_for_best_model="macro_f1",
            fp16=True,
            seed=base_data["seed"],
            logging_steps=10,
            report_to=base_data["report_to"],
            skip_memory_metrics=True,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_ds[fold],
            eval_dataset=val_ds[fold],
            compute_metrics=compute_metrics,
            callbacks=[EarlyStoppingCallback(early_stopping_patience=10)],
        )

        trainer.train()
        eval_metrics = trainer.evaluate()
        f1_scores.append(eval_metrics["eval_macro_f1"])


        fold_time_min = (time.time() - fold_start) / 60
        fold_times_min.append(fold_time_min)
        print(
            f"Trial {trial.number} | Fold {fold} | "
            f"F1={eval_metrics['eval_macro_f1']:.4f} | "
            f"Time={fold_time_min:.2f} min"
        )

        del trainer
        del model
        torch.cuda.empty_cache()

    return float(np.mean(f1_scores))

# study definition
db_path = here("results/optuna/optuna_study_roberta_lora.db")
storage_url = f"sqlite:///{db_path}"
n_startup_trials = 5

print(storage_url)

study = optuna.create_study(
    direction="maximize",
    sampler=optuna.samplers.TPESampler(
        n_startup_trials=n_startup_trials,
        seed=42,
    ),
    study_name="roberta-lora-hyperparameter-search",
    storage=storage_url,
    load_if_exists=True
)

study.optimize(objective, n_trials=10) #adding 10 more trials because did 40 before

# best trials
print(f"\n{'='*60}")
print(f"  Best macro_f1: {study.best_trial.value:.4f}")
print(f"  Best params:   {study.best_trial.params}")
print(f"{'='*60}")

/workspace/exaggeration-detection/src/data_holdout.py:65: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(ENCODED_LABELS)
Map: 100%|██████████| 424/424 [00:00<00:00, 16346.80 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 17365.01 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 17106.76 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 17333.86 examples/s]
Map: 100%|██████████| 424/424 [00:00<00:00, 17347.22 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 9943.78 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 12510.80 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 11737.89 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 11731.39 examples/s]
Map: 100%|██████████| 106/106 [00:00<00:00, 11836.96 examples/s]
[I 2026-03-23 20:27:41,351] Using an existing study with name 'roberta-lora-hyperparameter-search' instead of creating a new one.

Fold 0: train=424 val=106
Fold 1: train=424 val=106
Fold 2: train=424 val=106
Fold 3: train=424 val=106
Fold 4: train=424 val=106
sqlite:////workspace/exaggeration-detection/results/optuna/optuna_study_roberta_lora.db

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1361.53it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 45 | Fold 0 | F1=0.4121 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1687.35it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 45 | Fold 1 | F1=0.4245 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1380.09it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:29:33,014] Trial 45 finished with value: 0.42927426719557843 and parameters: {'learning_rate': 0.00039768386198768486, 'per_device_train_batch_size': 8, 'weight_decay': 0.030247809310584614, 'warmup_ratio': 0.12075520295779173, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 45 | Fold 3 | F1=0.4512 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1382.96it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 46 | Fold 0 | F1=0.4591 | Time=0.61 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1450.19it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 46 | Fold 1 | F1=0.4501 | Time=0.63 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1362.17it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:31:25,047] Trial 46 finished with value: 0.4412061196178196 and parameters: {'learning_rate': 0.00032747611144465813, 'per_device_train_batch_size': 8, 'weight_decay': 0.03739686069292883, 'warmup_ratio': 0.08245893005795087, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 46 | Fold 3 | F1=0.4144 | Time=0.63 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2288.61it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 47 | Fold 0 | F1=0.4048 | Time=0.61 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1685.02it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 47 | Fold 1 | F1=0.4393 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1764.34it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:33:15,888] Trial 47 finished with value: 0.42296979882792235 and parameters: {'learning_rate': 0.00022467447228881958, 'per_device_train_batch_size': 8, 'weight_decay': 0.01345592569693254, 'warmup_ratio': 0.09309780884119004, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 47 | Fold 3 | F1=0.4249 | Time=0.61 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1250.04it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 48 | Fold 0 | F1=0.4364 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1654.12it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 48 | Fold 1 | F1=0.5215 | Time=0.61 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2772.67it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:35:06,059] Trial 48 finished with value: 0.47040315759472473 and parameters: {'learning_rate': 0.00043550325334531636, 'per_device_train_batch_size': 8, 'weight_decay': 0.06513645328826949, 'warmup_ratio': 0.13465126101450825, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 48 | Fold 3 | F1=0.4532 | Time=0.61 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1472.76it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,920,003 || all params: 126,567,942 || trainable%: 1.5170

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 49 | Fold 0 | F1=0.3972 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1527.79it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 49 | Fold 1 | F1=0.4210 | Time=0.63 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 3417.66it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:36:58,040] Trial 49 finished with value: 0.3572133376971185 and parameters: {'learning_rate': 0.0004891192208895317, 'per_device_train_batch_size': 8, 'weight_decay': 0.07267402686301326, 'warmup_ratio': 0.13814525842839767, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 49 | Fold 3 | F1=0.2534 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1369.92it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 50 | Fold 0 | F1=0.2534 | Time=0.70 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1594.75it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 50 | Fold 1 | F1=0.2534 | Time=0.70 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1364.47it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:39:03,984] Trial 50 finished with value: 0.253411306042885 and parameters: {'learning_rate': 1.1287979335589331e-05, 'per_device_train_batch_size': 8, 'weight_decay': 0.06592446346977404, 'warmup_ratio': 0.06351152025014373, 'lora_r': 2, 'lora_alpha': 32, 'lora_dropout': 0.1}. Best is trial 20 with value: 0.4949775285111037.

Trial 50 | Fold 3 | F1=0.2534 | Time=0.70 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1407.87it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 51 | Fold 0 | F1=0.3641 | Time=0.63 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2267.83it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 51 | Fold 1 | F1=0.3721 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1839.80it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:40:55,602] Trial 51 finished with value: 0.3778444511168189 and parameters: {'learning_rate': 0.00026883950298415546, 'per_device_train_batch_size': 8, 'weight_decay': 0.05880128720742196, 'warmup_ratio': 0.14312760202802932, 'lora_r': 2, 'lora_alpha': 4, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 51 | Fold 3 | F1=0.3973 | Time=0.61 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1342.91it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 3,247,107 || all params: 127,895,046 || trainable%: 2.5389

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 52 | Fold 0 | F1=0.4143 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1439.16it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 52 | Fold 1 | F1=0.4583 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1974.29it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:42:47,633] Trial 52 finished with value: 0.4355648871627979 and parameters: {'learning_rate': 0.00043552488849296124, 'per_device_train_batch_size': 8, 'weight_decay': 0.06463605100146631, 'warmup_ratio': 0.0739565610877398, 'lora_r': 16, 'lora_alpha': 16, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 52 | Fold 3 | F1=0.4341 | Time=0.63 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1394.20it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 53 | Fold 0 | F1=0.4084 | Time=0.70 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2301.29it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 53 | Fold 1 | F1=0.3624 | Time=0.68 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1599.76it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:44:52,214] Trial 53 finished with value: 0.38303976105444265 and parameters: {'learning_rate': 0.0001649156711745393, 'per_device_train_batch_size': 8, 'weight_decay': 0.08145901286801432, 'warmup_ratio': 0.16125042592368935, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.1}. Best is trial 20 with value: 0.4949775285111037.

Trial 53 | Fold 3 | F1=0.3783 | Time=0.70 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2381.44it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 924,675 || all params: 125,572,614 || trainable%: 0.7364

Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 54 | Fold 0 | F1=0.4682 | Time=0.63 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 3152.17it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

Trial 54 | Fold 1 | F1=0.2534 | Time=0.62 min

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 2356.15it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
Using EarlyStoppingCallback without load_best_model_at_end=True. Once training is finished, the best model will not be loaded automatically.

[I 2026-03-23 20:46:44,091] Trial 54 finished with value: 0.3250187699689417 and parameters: {'learning_rate': 0.0004145312748290846, 'per_device_train_batch_size': 8, 'weight_decay': 0.07353548817687415, 'warmup_ratio': 0.12778648288561972, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.0}. Best is trial 20 with value: 0.4949775285111037.

Trial 54 | Fold 3 | F1=0.2534 | Time=0.62 min

============================================================
  Best macro_f1: 0.4950
  Best params:   {'learning_rate': 0.0004967831504102713, 'per_device_train_batch_size': 8, 'weight_decay': 0.04558767968874666, 'warmup_ratio': 0.12016661619597607, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.05}
============================================================

In [20]:
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=3)

linear_names = []
for name, module in model.named_modules():
    if module.__class__.__name__ == "Linear":
        linear_names.append(name)

for n in linear_names:
    print(n)

Loading weights: 100%|██████████| 197/197 [00:00<00:00, 1408.49it/s, Materializing param=roberta.encoder.layer.11.output.dense.weight]
RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.dense.bias              | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

roberta.encoder.layer.0.attention.self.query
roberta.encoder.layer.0.attention.self.key
roberta.encoder.layer.0.attention.self.value
roberta.encoder.layer.0.attention.output.dense
roberta.encoder.layer.0.intermediate.dense
roberta.encoder.layer.0.output.dense
roberta.encoder.layer.1.attention.self.query
roberta.encoder.layer.1.attention.self.key
roberta.encoder.layer.1.attention.self.value
roberta.encoder.layer.1.attention.output.dense
roberta.encoder.layer.1.intermediate.dense
roberta.encoder.layer.1.output.dense
roberta.encoder.layer.2.attention.self.query
roberta.encoder.layer.2.attention.self.key
roberta.encoder.layer.2.attention.self.value
roberta.encoder.layer.2.attention.output.dense
roberta.encoder.layer.2.intermediate.dense
roberta.encoder.layer.2.output.dense
roberta.encoder.layer.3.attention.self.query
roberta.encoder.layer.3.attention.self.key
roberta.encoder.layer.3.attention.self.value
roberta.encoder.layer.3.attention.output.dense
roberta.encoder.layer.3.intermediate.dense
roberta.encoder.layer.3.output.dense
roberta.encoder.layer.4.attention.self.query
roberta.encoder.layer.4.attention.self.key
roberta.encoder.layer.4.attention.self.value
roberta.encoder.layer.4.attention.output.dense
roberta.encoder.layer.4.intermediate.dense
roberta.encoder.layer.4.output.dense
roberta.encoder.layer.5.attention.self.query
roberta.encoder.layer.5.attention.self.key
roberta.encoder.layer.5.attention.self.value
roberta.encoder.layer.5.attention.output.dense
roberta.encoder.layer.5.intermediate.dense
roberta.encoder.layer.5.output.dense
roberta.encoder.layer.6.attention.self.query
roberta.encoder.layer.6.attention.self.key
roberta.encoder.layer.6.attention.self.value
roberta.encoder.layer.6.attention.output.dense
roberta.encoder.layer.6.intermediate.dense
roberta.encoder.layer.6.output.dense
roberta.encoder.layer.7.attention.self.query
roberta.encoder.layer.7.attention.self.key
roberta.encoder.layer.7.attention.self.value
roberta.encoder.layer.7.attention.output.dense
roberta.encoder.layer.7.intermediate.dense
roberta.encoder.layer.7.output.dense
roberta.encoder.layer.8.attention.self.query
roberta.encoder.layer.8.attention.self.key
roberta.encoder.layer.8.attention.self.value
roberta.encoder.layer.8.attention.output.dense
roberta.encoder.layer.8.intermediate.dense
roberta.encoder.layer.8.output.dense
roberta.encoder.layer.9.attention.self.query
roberta.encoder.layer.9.attention.self.key
roberta.encoder.layer.9.attention.self.value
roberta.encoder.layer.9.attention.output.dense
roberta.encoder.layer.9.intermediate.dense
roberta.encoder.layer.9.output.dense
roberta.encoder.layer.10.attention.self.query
roberta.encoder.layer.10.attention.self.key
roberta.encoder.layer.10.attention.self.value
roberta.encoder.layer.10.attention.output.dense
roberta.encoder.layer.10.intermediate.dense
roberta.encoder.layer.10.output.dense
roberta.encoder.layer.11.attention.self.query
roberta.encoder.layer.11.attention.self.key
roberta.encoder.layer.11.attention.self.value
roberta.encoder.layer.11.attention.output.dense
roberta.encoder.layer.11.intermediate.dense
roberta.encoder.layer.11.output.dense
classifier.dense
classifier.out_proj

In [27]:

print(study.best_trial)
print(study.best_value)
print(study.best_params)

FrozenTrial(number=20, state=<TrialState.COMPLETE: 1>, values=[0.4949775285111037], datetime_start=datetime.datetime(2026, 3, 23, 19, 28, 32, 703837), datetime_complete=datetime.datetime(2026, 3, 23, 19, 30, 37, 468875), params={'learning_rate': 0.0004967831504102713, 'per_device_train_batch_size': 8, 'weight_decay': 0.04558767968874666, 'warmup_ratio': 0.12016661619597607, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.05}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'learning_rate': FloatDistribution(high=0.0005, log=True, low=1e-05, step=None), 'per_device_train_batch_size': CategoricalDistribution(choices=(8,)), 'weight_decay': FloatDistribution(high=0.1, log=False, low=0.0, step=None), 'warmup_ratio': FloatDistribution(high=0.2, log=False, low=0.05, step=None), 'lora_r': CategoricalDistribution(choices=(2, 4, 8, 16)), 'lora_alpha': CategoricalDistribution(choices=(4, 8, 16, 32)), 'lora_dropout': CategoricalDistribution(choices=(0.0, 0.05, 0.1))}, trial_id=21, value=None)
0.4949775285111037
{'learning_rate': 0.0004967831504102713, 'per_device_train_batch_size': 8, 'weight_decay': 0.04558767968874666, 'warmup_ratio': 0.12016661619597607, 'lora_r': 2, 'lora_alpha': 16, 'lora_dropout': 0.05}